name: MVVMCDemo
options:
  bundleIdPrefix: com.joe.mvvmc
  deploymentTarget:
    iOS: "17.0"

targets:
  MVVMCDemo:
    type: application
    platform: iOS
    sources:
      - Sources
    info:
      path: Sources/App/Info.plist
      properties:
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.joe.mvvmc.demo
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_STRICT_CONCURRENCY: targeted
